; This file was auto-generated by drush make
core = 7.x

api = 2
projects[drupal][version] = "7.34"

; Modules
projects[backup_migrate][version] = "3.0"

projects[service_links][version] = "2.2"

projects[ctools][version] = "1.6"

projects[ckeditor][version] = "1.16"

projects[context][version] = "3.6"

projects[date][version] = "2.8"

projects[diff][version] = "3.2"

projects[draggableviews][version] = "2.1"

projects[ds][version] = "2.7"

projects[eck][version] = "2.0-rc7"

projects[entity][version] = "1.6"

projects[entity_translation][version] = "1.0-beta4"

projects[entitycache][version] = "1.2"

projects[entityreference][version] = "1.1"

projects[fast_404][version] = "1.4"

projects[features][version] = "2.3"

projects[field_collection][version] = "1.0-beta8"

projects[field_formatter_css_class][version] = "1.3"

projects[field_formatter_settings][version] = "1.1"

projects[field_group][version] = "1.4"

projects[field_wrappers][version] = "1.0"

projects[flexslider][version] = "2.0-alpha3"

projects[flexslider_field_collection][version] = "1.1"

projects[flexslider_views_slideshow][version] = "2.x-dev"

projects[globalredirect][version] = "1.5"

projects[google_analytics][version] = "2.1"

projects[i18n][version] = "1.12"

projects[inline_entity_form][version] = "1.5"

projects[jquery_update][version] = "2.5"

projects[l10n_update][version] = "1.1"

projects[libraries][version] = "2.2"

projects[link][version] = "1.3"

projects[metatag][version] = "1.4"

projects[module_filter][version] = "2.0"

projects[references][version] = "2.1"

projects[pathauto][version] = "1.2"

projects[responsive_menus][version] = "1.5"

projects[services][version] = "3.11"

projects[retina_images][version] = "1.0-beta4"

projects[rules][version] = "2.8"

projects[services_views][version] = "1.0"

projects[simplenews][version] = "1.1"

projects[superfish][version] = "1.9"

projects[title][version] = "1.0-alpha7"

projects[token][version] = "1.6"

projects[token_insert][version] = "2.4"

projects[variable][version] = "2.5"

projects[views][version] = "3.10"

projects[views_data_export][version] = "3.0-beta8"

projects[views_slideshow][version] = "3.1"

projects[views_system][version] = "3.2"

projects[webform][version] = "4.3"

projects[xmlsitemap][version] = "2.2"

; Themes
projects[bootstrap][version] = "3.0"

; Please fill the following out. Type may be one of get, git, bzr or svn,
; and url is the url of the download.
projects[bootstrap_subtheme][download][type] = ""
projects[bootstrap_subtheme][download][url] = ""
projects[bootstrap_subtheme][type] = "theme"

